name: candy_smash
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any
  go_router: any
  freezed_annotation: any
  json_annotation: any
  dio: any
  flutter_animate: any
flutter:
  uses-material-design: true
